Create readme.md
o-andres-m/Precio_Dolar pull request #3
Opened 2022-06-26 17:57 UTC by o-andres-m

Close #1

2022-06-26 18:03 UTC, jnasselle requested changes

2022-06-26 18:03 UTC, jnasselle commented on readme.md
> +Seleccionar desde el menu la opcion deseada, se imprime en pantalla el precio del dolar.
Change language to English

2022-07-01 21:20 UTC, o-andres-m commented
Hi Nicolas, i make the changes. Tell me about that.. Thanks!

2022-07-03 22:31 UTC, jnasselle approved these changes
Nice job @o-andres-m ,

Despite there's a lot of things to improve, the first lesson is to atomize the PRs changes to issue scope. In this case, multiple things were also solved.

New findings will be attacked on new issues

2022-07-03 22:32 UTC, merged